version: "3.9"

services:
  traefik:
    image: docker.io/library/traefik:v2.8.3@sha256:ad8c1935c4b901e10b62b6868d6369218793c69e7a7ea9c1d036fdc2b919e38e
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    read_only: true
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      resources:
        limits:
          memory: 128m

  fhir:
    image: docker.io/hapiproject/hapi:v6.1.0@sha256:253f87bb1f5b7627f8e25f76a4b0aa7a83f31968c6e111ad74d3cc4ad9ae812e
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    deploy:
      resources:
        limits:
          memory: 2048m
    read_only: true
    tmpfs:
      - /tmp
      - /app/target
    privileged: false
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "false"
      HAPI_FHIR_USE_APACHE_ADDRESS_STRATEGY: "true"
      HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_DELETE: "false"
      HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_WRITE: "false"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"
      HAPI_FHIR_ALLOW_MULTIPLE_DELETE: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.fhir.loadbalancer.server.port=8080"
      - "traefik.http.routers.fhir.rule=Host(`recruit-fhir-server.127.0.0.1.nip.io`)"
      - "traefik.http.routers.fhir.entrypoints=web"

  omopdb:
    image: quay.io/miracum/omop:test-data-v3@sha256:34919d66facaff8b1e56d8cb3cd9ac649ca6420aa86740ae9e32dff1b2b6eb26
    ports:
      - "127.0.0.1:25432:5432"

  ohdsi-webapi:
    image: docker.io/ohdsi/webapi:2.11.1@sha256:9bcb5003e6504669b53c94f3e0b4aa6ad9b5c78741f772ca402579632ce64fb3
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 4096m
    read_only: true
    tmpfs:
      - /tmp
    privileged: false
    environment:
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
      SECURITY_PROVIDER: "AtlasRegularSecurity"
      SECURITY_DB_DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      SECURITY_CORS_ENABLED: "true"
      SECURITY_ORIGIN: "*"
      SECURITY_DB_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SECURITY_DB_DATASOURCE_SCHEMA: ohdsi
      SECURITY_DB_DATASOURCE_USERNAME: postgres
      SECURITY_DB_DATASOURCE_PASSWORD: postgres
      SECURITY_DB_DATASOURCE_AUTHENTICATIONQUERY: >-
        SELECT password, first_name AS firstname, middle_name AS middlename, last_name AS lastname, username
        FROM ohdsi.basic_security_users
        WHERE username = ?
    depends_on:
      - omopdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ohdsi-webapi.rule=Host(`recruit-ohdsi.127.0.0.1.nip.io`) && PathPrefix(`/WebAPI`)"
      - "traefik.http.routers.ohdsi-webapi.entrypoints=web"

  ohdsi-atlas:
    image: docker.io/ohdsi/atlas:2.11.1@sha256:36df31ecd1c92f2f2d66535ff759e7626545179696a3f291f35dc75c14017564
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 64m
          cpus: "1"
    privileged: false
    volumes:
      - ./config-local.js:/usr/share/nginx/html/atlas/js/config-local.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ohdsi-atlas.rule=Host(`recruit-ohdsi.127.0.0.1.nip.io`) && PathPrefix(`/atlas`)"
      - "traefik.http.routers.ohdsi-atlas.entrypoints=web"

  list:
    image: ghcr.io/miracum/recruit/list:v2.15.5@sha256:1d076650cbf2f364235e49203a98015d35443d72e74f462085ea3bcedd25cb4c
    ports:
      - "127.0.0.1:8085:8080"
    environment:
      FHIR_URL: "http://fhir:8080/fhir"
      KEYCLOAK_DISABLED: "true"
      TRACING_ENABLED: "true"
      OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.37@sha256:60ab2e6b0682f79a4e42b2bd2526ac4de80a3a7a1ef136c71dc0cb85e9c50f46
    ports:
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:6831:6831/udp"
      - "127.0.0.1:6832:6832/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.127.0.0.1.nip.io`)"
      - "traefik.http.routers.jaeger.entrypoints=web"

  maildev:
    image: docker.io/maildev/maildev:2.0.5@sha256:082ec5ee92266c6e17493998ff1bf1c3eb70604b159fbeeaa435ee777f5cc953
    restart: unless-stopped
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    deploy:
      resources:
        limits:
          memory: 64m
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - "3025:1025"
      - "2080:1080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.maildev.loadbalancer.server.port=1080"
      - "traefik.http.routers.maildev.rule=Host(`maildev.127.0.0.1.nip.io`)"
      - "traefik.http.routers.maildev.entrypoints=web"

  jobstore-db:
    image: docker.io/library/postgres:14.5@sha256:f8816ada742348e1adfcec5c2a180b675bf6e4a294e0feb68bd70179451e1242
    environment:
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
      POSTGRES_DB: recruit_notify_jobs
    ports:
      - "127.0.0.1:6432:5432"
