name: "Build Jib container image"
description: "Build container image for Java modules using Jib and upload the resulting image tar as an artifact"
inputs:
  project-name:
    description: "Name of the project inside the /src/ dir"
    required: true
  working-directory:
    description: "Working directory to run `./gradlew build` etc. in"
    default: ./src
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # tag=v3.4.1
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@356abb47e7664b5505e25d7997a5a522a17c62d9 # tag=v2.3.0

    - name: Build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ./gradlew :${{ inputs.project-name }}:build

    - name: Generate test report
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ./gradlew :${{ inputs.project-name }}:jacocoTestReport

    - name: Build container image
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ./gradlew :${{ inputs.project-name }}:downloadOpenTelemetryJavaAgent
        ./gradlew -Djib.console=plain :${{ inputs.project-name }}:jibBuildTar

    - name: Upload container image
      uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3.1.0
      with:
        name: ${{ inputs.project-name }}-build-artifacts
        path: |
          ${{ inputs.working-directory }}/${{ inputs.project-name }}/build/jib-image.tar
          ${{ inputs.working-directory }}/${{ inputs.project-name }}/build/jib-image.json
