---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-recruit-images
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: check-recruit-images
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "ghcr.io/miracum/recruit/list:*"
            - "ghcr.io/miracum/recruit/notify:*"
            - "ghcr.io/miracum/recruit/query:*"
            - "ghcr.io/chgl/recruit-release-test/list:*"
            - "ghcr.io/chgl/recruit-release-test/notify:*"
            - "ghcr.io/chgl/recruit-release-test/query:*"
          attestors:
            - entries:
                - keyless:
                    subject: "https://github.com/chgl/recruit-release-test/.github/workflows/build.yaml@refs/tags/*"
                    issuer: "https://token.actions.githubusercontent.com"
                    rekor:
                      url: https://rekor.sigstore.dev
                    additionalExtensions:
                      githubWorkflowTrigger: release
                      githubWorkflowName: ci
                      githubWorkflowRepository: chgl/recruit-release-test
          # attestations:
          #   - predicateType: https://slsa.dev/provenance/v0.2
          #     conditions:
          #       - all:
          #           - key: "{{ repo.uri }}"
          #             operator: Equals
          #             value: "https://git-repo.com/org/app"
          #           - key: "{{ repo.branch }}"
          #             operator: Equals
          #             value: "main"
          #           - key: "{{ reviewers }}"
          #             operator: In
          #             value: ["ana@example.com", "bob@example.com"]
