<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode>true</RestoreLockedMode>
    <!-- x-release-please-start-version -->
    <Version>10.5.7</Version>
    <!-- x-release-please-end -->
    <Company>miracum.org</Company>
    <Description>Patient recruitment on FHIR.</Description>
    <Copyright>© miracum.org. All rights reserved.</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Authors>miracum.org</Authors>
  </PropertyGroup>
</Project>
