<Project>
  <ItemGroup>
    <PackageVersion Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageVersion Include="BlazorBlueprint.Components" Version="3.15.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageVersion Include="Hangfire.AspNetCore" Version="1.8.24" />
    <PackageVersion Include="Hangfire.PostgreSql" Version="1.21.1" />
    <PackageVersion Include="Hl7.Fhir.R4" Version="6.4.0" />
    <PackageVersion Include="HtmlSanitizer" Version="9.1.982" />
    <PackageVersion Include="io.github.diz-uker.fhir-ig-constants" Version="0.2.15" />
    <PackageVersion Include="io.github.diz-uker.ig-codegen-core" Version="0.2.15" />
    <PackageVersion Include="MailKit" Version="4.17.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.4" />
    <PackageVersion
      Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore"
      Version="10.0.11"
    />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="Mjml.Net" Version="4.14.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
    <PackageVersion
      Include="OpenTelemetry.Exporter.Prometheus.AspNetCore"
      Version="1.17.0-beta.1"
    />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.17.0" />
    <PackageVersion Include="Slugify.Core" Version="5.1.1" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.14.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
