remote: origin
lint-conf: .github/ct/lintconf.yaml
chart-yaml-schema: .github/ct/chart-schema.yaml
validate-maintainers: false
validate-chart-schema: true
validate-yaml: true
# versioning is done by release-please, so we don't have to check version bumps
# on every PR
check-version-increment: false
chart-dirs:
  - charts
helm-extra-args: --timeout 300s
upgrade: true
skip-missing-values: true
release-label: release
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
release-notes-file: CHANGELOG.md
