list:
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
  ingress:
    enabled: true
    hosts:
      - host: recruit-list.127.0.0.1.nip.io
        paths: ["/"]

fhirserver:
  resources:
    requests:
      memory: "3Gi"
      cpu: "2500m"
    limits:
      memory: "3Gi"
  postgresql:
    auth:
      postgresPassword: fhir
  ingress:
    enabled: true
    hosts:
      - host: recruit-fhir-server.127.0.0.1.nip.io
        paths: ["/"]

query:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
  webAPI:
    dataSource: "SynPUF-CDMV5"
  omop:
    resultsSchema: synpuf_results
    cdmSchema: synpuf_cdm
  cohortSelectorLabels:
    - "recruIT"

notify:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
  rules:
    schedules:
      everyMorning: "0 0 8 1/1 * ? *"
    trials:
      - acronym: "*"
        subscriptions:
          - email: "everything@example.com"
      - acronym: "SAMPLE"
        accessibleBy:
          users:
            - "user1"
            - "user.two@example.com"
        subscriptions:
          - email: "everyMorning@example.com"
            notify: "everyMorning"

mailhog:
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "64Mi"
  ingress:
    enabled: true
    hosts:
      - host: recruit-mailhog.127.0.0.1.nip.io
        paths:
          - path: "/"
            pathType: Prefix

ohdsi:
  atlas:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "64Mi"
  webApi:
    resources:
      requests:
        memory: "4Gi"
        cpu: "250m"
      limits:
        memory: "4Gi"
  postgresql:
    auth:
      postgresPassword: ohdsi
    primary:
      resources:
        limits:
          memory: 4Gi
          cpu: 2500m
        requests:
          memory: 256Mi
          cpu: 250m
  ingress:
    enabled: true
    hosts:
      - host: recruit-ohdsi.127.0.0.1.nip.io
  cdmInitJob:
    enabled: false
    ttlSecondsAfterFinished: ""
    extraEnv:
      - name: SETUP_SYNPUF
        value: "true"
  achilles:
    schemas:
      cdm: "synpuf_cdm"
      vocab: "synpuf_cdm"
      res: "synpuf_results"
    sourceName: "SynPUF-CDMV5"
