podAnnotations:
  linkerd.io/inject: "enabled"

postgresql:
  primary:
    service:
      annotations:
        config.linkerd.io/opaque-ports: "5432"

ohdsi:
  postgresql:
    primary:
      service:
        annotations:
          config.linkerd.io/opaque-ports: "5432"
  atlas:
    podAnnotations:
      linkerd.io/inject: "enabled"
  webApi:
    podAnnotations:
      linkerd.io/inject: "enabled"

fhirserver:
  postgresql:
    primary:
      service:
        annotations:
          config.linkerd.io/opaque-ports: "5432"
  podAnnotations:
    linkerd.io/inject: "enabled"

mailhog:
  automountServiceAccountToken: true
  podAnnotations:
    linkerd.io/inject: "enabled"
  service:
    annotations:
      config.linkerd.io/opaque-ports: "1025"
