list:
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
  ingress:
    enabled: true
    hosts:
      - host: recruit-list.127.0.0.1.nip.io
        paths: ["/"]

fhirserver:
  resources:
    requests:
      memory: "3Gi"
      cpu: "2500m"
    limits:
      memory: "3Gi"
  postgresql:
    auth:
      postgresPassword: fhir
  ingress:
    enabled: true
    hosts:
      - host: recruit-fhir-server.127.0.0.1.nip.io
        paths: ["/"]

query:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
  webAPI:
    dataSource: "SynPUF-CDMV5"
  omop:
    resultsSchema: synpuf_results
    cdmSchema: synpuf_cdm
  cohortSelectorLabels:
    - "recruIT"

notify:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
    limits:
      memory: "1Gi"
  rules:
    schedules:
      everyMorning: "0 0 8 1/1 * ? *"
    trials:
      - acronym: "*"
        subscriptions:
          - email: "everything@example.com"
      - acronym: "SAMPLE"
        accessibleBy:
          users:
            - "user1"
            - "user.two@example.com"
        subscriptions:
          - email: "everyMorning@example.com"
            notify: "everyMorning"

mailhog:
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "64Mi"
  ingress:
    enabled: true
    hosts:
      - host: recruit-mailhog.127.0.0.1.nip.io
        paths:
          - path: "/"
            pathType: Prefix

ohdsi:
  atlas:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "64Mi"
  webApi:
    resources:
      requests:
        memory: "4Gi"
        cpu: "250m"
      limits:
        memory: "4Gi"
  postgresql:
    auth:
      postgresPassword: ohdsi
    primary:
      resources:
        limits:
          memory: 4Gi
          cpu: 2500m
        requests:
          memory: 256Mi
          cpu: 250m
  ingress:
    enabled: true
    hosts:
      - host: recruit-ohdsi.127.0.0.1.nip.io
  cdmInitJob:
    enabled: false
    ttlSecondsAfterFinished: ""
    extraEnv:
      - name: SETUP_SYNPUF
        value: "true"
  achilles:
    schemas:
      cdm: "synpuf_cdm"
      vocab: "synpuf_cdm"
      res: "synpuf_results"
    sourceName: "SynPUF-CDMV5"
  loadCohortDefinitionsJob:
    enabled: false
    cohortDefinitions:
      - |
        {
          "name": "A sample cohort",
          "description": "[acronym=SAMPLE] [recruIT] Sample Cohort containing only female patients older than 90 years.",
          "expressionType": "SIMPLE_EXPRESSION",
          "expression": {
            "ConceptSets": [],
            "PrimaryCriteria": {
              "CriteriaList": [
                {
                  "ObservationPeriod": {
                    "First": true
                  }
                }
              ],
              "ObservationWindow": {
                "PriorDays": 0,
                "PostDays": 0
              },
              "PrimaryCriteriaLimit": {
                "Type": "First"
              }
            },
            "QualifiedLimit": {
              "Type": "First"
            },
            "ExpressionLimit": {
              "Type": "First"
            },
            "InclusionRules": [
              {
                "name": "Older than 18",
                "expression": {
                  "Type": "ALL",
                  "CriteriaList": [],
                  "DemographicCriteriaList": [
                    {
                      "Age": {
                        "Value": 90,
                        "Op": "gt"
                      },
                      "Gender": [
                        {
                          "CONCEPT_CODE": "F",
                          "CONCEPT_ID": 8532,
                          "CONCEPT_NAME": "FEMALE",
                          "DOMAIN_ID": "Gender",
                          "INVALID_REASON_CAPTION": "Unknown",
                          "STANDARD_CONCEPT_CAPTION": "Unknown",
                          "VOCABULARY_ID": "Gender"
                        }
                      ]
                    }
                  ],
                  "Groups": []
                }
              }
            ],
            "CensoringCriteria": [],
            "CollapseSettings": {
              "CollapseType": "ERA",
              "EraPad": 0
            },
            "CensorWindow": {},
            "cdmVersionRange": ">=5.0.0"
          }
        }
