// Generated by ig-codegen from io.github.miracum.recruit 0.1.0. Do not edit directly.
package io.github.miracum.recruit;

import java.util.Optional;
import org.hl7.fhir.instance.model.api.IBaseHasExtensions;
import org.hl7.fhir.r4.model.Coding;
import org.hl7.fhir.r4.model.Extension;
import org.hl7.fhir.r4.model.Reference;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

public final class Recruit {
  private Recruit() {
  }

  public static final class CodeSystems {
    private CodeSystems() {
    }

    /**
     * The canonical URL {@code https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category}.
     *
     * @return {@code https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category}
     */
    public static String eligibilityAssessmentCategory() {
      return "https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category";
    }

    /**
     * The canonical URL {@code https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type}.
     *
     * @return {@code https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type}
     */
    public static String screeningListType() {
      return "https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type";
    }

    public enum EligibilityAssessmentCategory {
      /**
       * {@code eligibility-assessment} - Eligibility assessment
       */
      ELIGIBILITY_ASSESSMENT("eligibility-assessment", "Eligibility assessment");

      private final @NonNull String code;

      private final @Nullable String display;

      EligibilityAssessmentCategory(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return the CodeSystem URL {@code https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category}
       */
      public @NonNull String system(@NonNull EligibilityAssessmentCategory this) {
        return "https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category";
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category}
       */
      public @NonNull Coding coding(@NonNull EligibilityAssessmentCategory this) {
        return new Coding("https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category", code, display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if none matches
       */
      public static Optional<@NonNull EligibilityAssessmentCategory> fromValue(
          @NonNull String code) {
        for (EligibilityAssessmentCategory value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }

      /**
       * @param code the FHIR code to look up
       * @return the constant whose {@code code} matches
       * @throws IllegalArgumentException if no constant has that code
       */
      public static @NonNull EligibilityAssessmentCategory fromValueOrThrow(@NonNull String code) {
        return fromValue(code).orElseThrow(() -> new IllegalArgumentException("Unknown code: " + code));
      }
    }

    public enum ScreeningListType {
      /**
       * {@code screening-recommendations} - Screening recommendations
       */
      SCREENING_RECOMMENDATIONS("screening-recommendations", "Screening recommendations");

      private final @NonNull String code;

      private final @Nullable String display;

      ScreeningListType(@NonNull String code, @Nullable String display) {
        this.code = code;
        this.display = display;
      }

      /**
       * @return the CodeSystem URL {@code https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type}
       */
      public @NonNull String system(@NonNull ScreeningListType this) {
        return "https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type";
      }

      /**
       * @return a new {@link Coding} for this concept, with system {@code https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type}
       */
      public @NonNull Coding coding(@NonNull ScreeningListType this) {
        return new Coding("https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type", code, display);
      }

      /**
       * @param code the FHIR code to look up
       * @return an {@link Optional} containing the constant whose {@code code} matches, or empty if none matches
       */
      public static Optional<@NonNull ScreeningListType> fromValue(@NonNull String code) {
        for (ScreeningListType value : values()) {
          if (value.code.equals(code)) {
            return Optional.of(value);
          }
        }
        return Optional.empty();
      }

      /**
       * @param code the FHIR code to look up
       * @return the constant whose {@code code} matches
       * @throws IllegalArgumentException if no constant has that code
       */
      public static @NonNull ScreeningListType fromValueOrThrow(@NonNull String code) {
        return fromValue(code).orElseThrow(() -> new IllegalArgumentException("Unknown code: " + code));
      }
    }
  }

  public static final class Profiles {
    private Profiles() {
    }

    /**
     * The canonical URL {@code https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment}.
     *
     * @return {@code https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment}
     */
    public static String eligibilityAssessment() {
      return "https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment";
    }

    /**
     * The canonical URL {@code https://miracum.github.io/recruit/fhir/StructureDefinition/research-study}.
     *
     * @return {@code https://miracum.github.io/recruit/fhir/StructureDefinition/research-study}
     */
    public static String researchStudy() {
      return "https://miracum.github.io/recruit/fhir/StructureDefinition/research-study";
    }

    /**
     * The canonical URL {@code https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list}.
     *
     * @return {@code https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list}
     */
    public static String screeningList() {
      return "https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list";
    }
  }

  public static final class Extensions {
    private Extensions() {
    }

    /**
     * A new {@link Extension} for the canonical URL {@code https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library} and the given value
     */
    public static @NonNull Extension eligibilityAssessmentDerivedFromLibrary(
        @NonNull Reference value) {
      return new Extension("https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library", value);
    }

    /**
     * A new {@link Extension} for the canonical URL {@code https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study}.
     *
     * @param value the extension value
     * @return a new {@link Extension} with url {@code https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study} and the given value
     */
    public static @NonNull Extension screeningListBelongsToStudy(@NonNull Reference value) {
      return new Extension("https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study", value);
    }

    /**
     * Gets the value of extension {@code https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library} from {@code resource}, or {@code null} if absent.
     *
     * @param resource the resource or element to read from
     * @return the extension value, or {@code null}
     */
    public static @Nullable Reference getEligibilityAssessmentDerivedFromLibrary(
        @NonNull IBaseHasExtensions resource) {
      for (var e : resource.getExtension()) {
        if ("https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library".equals(e.getUrl())) {
          return (Reference) ((Extension) e).getValue();
        }
      }
      return null;
    }

    /**
     * Gets the value of extension {@code https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study} from {@code resource}, or {@code null} if absent.
     *
     * @param resource the resource or element to read from
     * @return the extension value, or {@code null}
     */
    public static @Nullable Reference getScreeningListBelongsToStudy(
        @NonNull IBaseHasExtensions resource) {
      for (var e : resource.getExtension()) {
        if ("https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study".equals(e.getUrl())) {
          return (Reference) ((Extension) e).getValue();
        }
      }
      return null;
    }

    public static final class Urls {
      private Urls() {
      }

      /**
       * @return the extension URL {@code https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library}
       */
      public static @NonNull String eligibilityAssessmentDerivedFromLibrary() {
        return "https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library";
      }

      /**
       * @return the extension URL {@code https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study}
       */
      public static @NonNull String screeningListBelongsToStudy() {
        return "https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study";
      }
    }
  }

  public static final class NamingSystems {
    private NamingSystems() {
    }

    /**
     * The identifier system for a per-criterion eligibility Observation's business identifier. Derived from the ResearchSubject identifier and the Library identifier of the eligibility criterion.
     */
    public static final class EligibilityAssessmentId {
      private EligibilityAssessmentId() {
      }

      /**
       * @return {@code https://miracum.github.io/recruit/fhir/identifiers/eligibility-assessment-id}
       */
      public static @NonNull String uri() {
        return "https://miracum.github.io/recruit/fhir/identifiers/eligibility-assessment-id";
      }
    }

    /**
     * The identifier system for the Group containing references to one or more eligibility criteria Library resources
     */
    public static final class EligibilityGroupId {
      private EligibilityGroupId() {
      }

      /**
       * @return {@code https://miracum.github.io/recruit/fhir/identifiers/eligibility-group-id}
       */
      public static @NonNull String uri() {
        return "https://miracum.github.io/recruit/fhir/identifiers/eligibility-group-id";
      }
    }

    /**
     * The identifier system for a criterion expressed in a Library resource
     */
    public static final class EligibilityLibraryId {
      private EligibilityLibraryId() {
      }

      /**
       * @return {@code https://miracum.github.io/recruit/fhir/identifiers/eligibility-library-id}
       */
      public static @NonNull String uri() {
        return "https://miracum.github.io/recruit/fhir/identifiers/eligibility-library-id";
      }
    }

    /**
     * The identifier system for a recruIT-created ResearchSubject's business identifier
     */
    public static final class ResearchSubjectId {
      private ResearchSubjectId() {
      }

      /**
       * @return {@code https://miracum.github.io/recruit/fhir/identifiers/research-subject-id}
       */
      public static @NonNull String uri() {
        return "https://miracum.github.io/recruit/fhir/identifiers/research-subject-id";
      }
    }

    /**
     * The identifier system for a screening List's business identifier, which is the study's own identifier - used as the conditional-update key for a study's screening List.
     */
    public static final class ScreeningListId {
      private ScreeningListId() {
      }

      /**
       * @return {@code https://miracum.github.io/recruit/fhir/identifiers/screening-list-id}
       */
      public static @NonNull String uri() {
        return "https://miracum.github.io/recruit/fhir/identifiers/screening-list-id";
      }
    }
  }
}
