{{- if .Values.list.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "recruit.fullname" . }}-list
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
  {{- with .Values.list.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
