spring:
  application:
    name: tester
  main:
    banner-mode: off

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %m %X %n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
