// Generated by ig-codegen from io.github.miracum.recruit 0.1.0. Do not edit directly.
using Hl7.Fhir.Model;

namespace RecruIT.FhirConstants;

public static class Recruit
{
    public static class CodeSystems
    {
        public static class Urls
        {
            /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category</c>.</summary>
            public static string EligibilityAssessmentCategory =>
                "https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category";

            /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type</c>.</summary>
            public static string ScreeningListType =>
                "https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type";

        }

        /// <summary>Concepts for <c>https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category</c>.</summary>
        public enum EligibilityAssessmentCategory
        {
            /// <summary><c>eligibility-assessment</c> - Eligibility assessment</summary>
            EligibilityAssessment,
        }

        /// <summary>Concepts for <c>https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type</c>.</summary>
        public enum ScreeningListType
        {
            /// <summary><c>screening-recommendations</c> - Screening recommendations</summary>
            ScreeningRecommendations,
        }
    }

    public static class Profiles
    {
        /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment</c>.</summary>
        public static string EligibilityAssessment => "https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment";

        /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/research-study</c>.</summary>
        public static string ResearchStudy => "https://miracum.github.io/recruit/fhir/StructureDefinition/research-study";

        /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list</c>.</summary>
        public static string ScreeningList => "https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list";

    }

    public static class Extensions
    {
        public static class Urls
        {
            /// <summary>The extension URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library</c>.</summary>
            public static string EligibilityAssessmentDerivedFromLibrary => "https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library";

            /// <summary>The extension URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study</c>.</summary>
            public static string ScreeningListBelongsToStudy => "https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study";

        }

        /// <summary>A new <see cref="Extension"/> for <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library</c>.</summary>
        /// <param name="value">The extension value.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library</c> and the given value.</returns>
        public static Extension EligibilityAssessmentDerivedFromLibrary(ResourceReference value) =>
            new("https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library", value);

        /// <summary>A new <see cref="Extension"/> for <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study</c>.</summary>
        /// <param name="value">The extension value.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study</c> and the given value.</returns>
        public static Extension ScreeningListBelongsToStudy(ResourceReference value) =>
            new("https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study", value);
    }

    public static class NamingSystems
    {
        /// <summary>The identifier system for a per-criterion eligibility Observation's business identifier. Derived from the ResearchSubject identifier and the Library identifier of the eligibility criterion.</summary>
        public static class EligibilityAssessmentId
        {
            /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/eligibility-assessment-id</c></summary>
            public static string Uri =>
                "https://miracum.github.io/recruit/fhir/identifiers/eligibility-assessment-id";
        }

        /// <summary>The identifier system for the Group containing references to one or more eligibility criteria Library resources</summary>
        public static class EligibilityGroupId
        {
            /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/eligibility-group-id</c></summary>
            public static string Uri =>
                "https://miracum.github.io/recruit/fhir/identifiers/eligibility-group-id";
        }

        /// <summary>The identifier system for a criterion expressed in a Library resource</summary>
        public static class EligibilityLibraryId
        {
            /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/eligibility-library-id</c></summary>
            public static string Uri =>
                "https://miracum.github.io/recruit/fhir/identifiers/eligibility-library-id";
        }

        /// <summary>The identifier system for a recruIT-created ResearchSubject's business identifier</summary>
        public static class ResearchSubjectId
        {
            /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/research-subject-id</c></summary>
            public static string Uri =>
                "https://miracum.github.io/recruit/fhir/identifiers/research-subject-id";
        }

        /// <summary>The identifier system for a screening List's business identifier, which is the study's own identifier - used as the conditional-update key for a study's screening List.</summary>
        public static class ScreeningListId
        {
            /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/screening-list-id</c></summary>
            public static string Uri =>
                "https://miracum.github.io/recruit/fhir/identifiers/screening-list-id";
        }

        /// <summary>The identifier system for a criterion expressed in a Library resource when synced from a Superset instance.</summary>
        public static class SupersetSyncedEligibilityLibraryId
        {
            /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/superset-synced-eligibility-library-id</c></summary>
            public static string Uri =>
                "https://miracum.github.io/recruit/fhir/identifiers/superset-synced-eligibility-library-id";
        }
    }
}

/// <summary>Extension methods for <see cref="Recruit.CodeSystems.EligibilityAssessmentCategory"/>.</summary>
public static class EligibilityAssessmentCategoryExtensions
{
    /// <returns>The CodeSystem URL <c>https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category</c>.</returns>
    public static string Url(this Recruit.CodeSystems.EligibilityAssessmentCategory _) =>
        "https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-assessment-category";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Recruit.CodeSystems.EligibilityAssessmentCategory value) => value switch
    {
        Recruit.CodeSystems.EligibilityAssessmentCategory.EligibilityAssessment => "eligibility-assessment",
        _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
    };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(this Recruit.CodeSystems.EligibilityAssessmentCategory value) => value switch
    {
        Recruit.CodeSystems.EligibilityAssessmentCategory.EligibilityAssessment => "Eligibility assessment",
        _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
    };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(this Recruit.CodeSystems.EligibilityAssessmentCategory value) =>
        new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Recruit.CodeSystems.EligibilityAssessmentCategory"/>, or <c>null</c> if none matches.</returns>
    public static Recruit.CodeSystems.EligibilityAssessmentCategory? FromValue(string code) => code switch
    {
        "eligibility-assessment" => Recruit.CodeSystems.EligibilityAssessmentCategory.EligibilityAssessment,
        _ => null
    };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Recruit.CodeSystems.EligibilityAssessmentCategory"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Recruit.CodeSystems.EligibilityAssessmentCategory FromValueOrThrow(string code) =>
        FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for <see cref="Recruit.CodeSystems.ScreeningListType"/>.</summary>
public static class ScreeningListTypeExtensions
{
    /// <returns>The CodeSystem URL <c>https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type</c>.</returns>
    public static string Url(this Recruit.CodeSystems.ScreeningListType _) =>
        "https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Recruit.CodeSystems.ScreeningListType value) => value switch
    {
        Recruit.CodeSystems.ScreeningListType.ScreeningRecommendations => "screening-recommendations",
        _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
    };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(this Recruit.CodeSystems.ScreeningListType value) => value switch
    {
        Recruit.CodeSystems.ScreeningListType.ScreeningRecommendations => "Screening recommendations",
        _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
    };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(this Recruit.CodeSystems.ScreeningListType value) =>
        new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Recruit.CodeSystems.ScreeningListType"/>, or <c>null</c> if none matches.</returns>
    public static Recruit.CodeSystems.ScreeningListType? FromValue(string code) => code switch
    {
        "screening-recommendations" => Recruit.CodeSystems.ScreeningListType.ScreeningRecommendations,
        _ => null
    };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Recruit.CodeSystems.ScreeningListType"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Recruit.CodeSystems.ScreeningListType FromValueOrThrow(string code) =>
        FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for reading <see cref="Recruit.Extensions"/> from FHIR resources.</summary>
public static class RecruitFhirExtensions
{
    /// <summary>Gets the value of extension <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static ResourceReference? GetEligibilityAssessmentDerivedFromLibrary(this IExtendable resource) =>
        resource.GetExtensionValue<ResourceReference>("https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-assessment-derived-from-library");

    /// <summary>Gets the value of extension <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static ResourceReference? GetScreeningListBelongsToStudy(this IExtendable resource) =>
        resource.GetExtensionValue<ResourceReference>("https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study");
}
