// Generated by ig-codegen from io.github.miracum.recruit 0.1.0. Do not edit directly.
using Hl7.Fhir.Model;

namespace Recruit;

public static class Recruit
{
    public static class CodeSystems
    {
        public static class Urls
        {
            /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-observation-category</c>.</summary>
            public static string EligibilityObservationCategory =>
                "https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-observation-category";

            /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type</c>.</summary>
            public static string ScreeningListType =>
                "https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type";
        }

        /// <summary>Concepts for <c>https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-observation-category</c>.</summary>
        public enum EligibilityObservationCategory
        {
            /// <summary><c>eligibility-assessment</c> - Eligibility assessment</summary>
            EligibilityAssessment,
        }

        /// <summary>Concepts for <c>https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type</c>.</summary>
        public enum ScreeningListType
        {
            /// <summary><c>screening-recommendations</c> - Screening recommendations</summary>
            ScreeningRecommendations,
        }
    }

    public static class Profiles
    {
        /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/research-study</c>.</summary>
        public static string ResearchStudy =>
            "https://miracum.github.io/recruit/fhir/StructureDefinition/research-study";

        /// <summary>The canonical URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list</c>.</summary>
        public static string ScreeningList =>
            "https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list";
    }

    public static class Extensions
    {
        public static class Urls
        {
            /// <summary>The extension URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-observation-derived-from-library</c>.</summary>
            public static string EligibilityObservationDerivedFromLibrary =>
                "https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-observation-derived-from-library";

            /// <summary>The extension URL <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study</c>.</summary>
            public static string ScreeningListBelongsToStudy =>
                "https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study";
        }

        /// <summary>A new <see cref="Extension"/> for <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-observation-derived-from-library</c>.</summary>
        /// <param name="value">The extension value.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-observation-derived-from-library</c> and the given value.</returns>
        public static Extension EligibilityObservationDerivedFromLibrary(ResourceReference value) =>
            new(
                "https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-observation-derived-from-library",
                value
            );

        /// <summary>A new <see cref="Extension"/> for <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study</c>.</summary>
        /// <param name="value">The extension value.</param>
        /// <returns>A new <see cref="Extension"/> with url <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study</c> and the given value.</returns>
        public static Extension ScreeningListBelongsToStudy(ResourceReference value) =>
            new(
                "https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study",
                value
            );
    }

    public static class NamingSystems
    {
        /// <summary>The identifier system for a per-criterion eligibility Observation's business identifier</summary>
        public static class EligibilityObservationId
        {
            public static class UniqueId
            {
                /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/eligibility-observation-id</c></summary>
                public static string Uri =>
                    "https://miracum.github.io/recruit/fhir/identifiers/eligibility-observation-id";
            }
        }

        /// <summary>The identifier system for a recruIT-created ResearchSubject's business identifier</summary>
        public static class ResearchSubjectId
        {
            public static class UniqueId
            {
                /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/research-subject-id</c></summary>
                public static string Uri =>
                    "https://miracum.github.io/recruit/fhir/identifiers/research-subject-id";
            }
        }

        /// <summary>The identifier system for a screening List's business identifier, which is the study's own identifier - used as the conditional-update key for a study's screening List.</summary>
        public static class ScreeningListId
        {
            public static class UniqueId
            {
                /// <summary><c>https://miracum.github.io/recruit/fhir/identifiers/screening-list-id</c></summary>
                public static string Uri =>
                    "https://miracum.github.io/recruit/fhir/identifiers/screening-list-id";
            }
        }
    }
}

/// <summary>Extension methods for <see cref="Recruit.CodeSystems.EligibilityObservationCategory"/>.</summary>
public static class EligibilityObservationCategoryExtensions
{
    /// <returns>The CodeSystem URL <c>https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-observation-category</c>.</returns>
    public static string Url(this Recruit.CodeSystems.EligibilityObservationCategory _) =>
        "https://miracum.github.io/recruit/fhir/CodeSystem/eligibility-observation-category";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Recruit.CodeSystems.EligibilityObservationCategory value) =>
        value switch
        {
            Recruit.CodeSystems.EligibilityObservationCategory.EligibilityAssessment =>
                "eligibility-assessment",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(this Recruit.CodeSystems.EligibilityObservationCategory value) =>
        value switch
        {
            Recruit.CodeSystems.EligibilityObservationCategory.EligibilityAssessment =>
                "Eligibility assessment",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(this Recruit.CodeSystems.EligibilityObservationCategory value) =>
        new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Recruit.CodeSystems.EligibilityObservationCategory"/>, or <c>null</c> if none matches.</returns>
    public static Recruit.CodeSystems.EligibilityObservationCategory? FromValue(string code) =>
        code switch
        {
            "eligibility-assessment" => Recruit
                .CodeSystems
                .EligibilityObservationCategory
                .EligibilityAssessment,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Recruit.CodeSystems.EligibilityObservationCategory"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Recruit.CodeSystems.EligibilityObservationCategory FromValueOrThrow(
        string code
    ) => FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for <see cref="Recruit.CodeSystems.ScreeningListType"/>.</summary>
public static class ScreeningListTypeExtensions
{
    /// <returns>The CodeSystem URL <c>https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type</c>.</returns>
    public static string Url(this Recruit.CodeSystems.ScreeningListType _) =>
        "https://miracum.github.io/recruit/fhir/CodeSystem/screening-list-type";

    /// <returns>The FHIR code for this concept.</returns>
    public static string Code(this Recruit.CodeSystems.ScreeningListType value) =>
        value switch
        {
            Recruit.CodeSystems.ScreeningListType.ScreeningRecommendations =>
                "screening-recommendations",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>The display label for this concept, or <c>null</c> if none.</returns>
    public static string? Display(this Recruit.CodeSystems.ScreeningListType value) =>
        value switch
        {
            Recruit.CodeSystems.ScreeningListType.ScreeningRecommendations =>
                "Screening recommendations",
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
        };

    /// <returns>A new <see cref="Coding"/> for this concept.</returns>
    public static Coding Coding(this Recruit.CodeSystems.ScreeningListType value) =>
        new(value.Url(), value.Code(), value.Display());

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Recruit.CodeSystems.ScreeningListType"/>, or <c>null</c> if none matches.</returns>
    public static Recruit.CodeSystems.ScreeningListType? FromValue(string code) =>
        code switch
        {
            "screening-recommendations" => Recruit
                .CodeSystems
                .ScreeningListType
                .ScreeningRecommendations,
            _ => null,
        };

    /// <param name="code">The FHIR code to look up.</param>
    /// <returns>The matching <see cref="Recruit.CodeSystems.ScreeningListType"/>.</returns>
    /// <exception cref="ArgumentException">If no constant has that code.</exception>
    public static Recruit.CodeSystems.ScreeningListType FromValueOrThrow(string code) =>
        FromValue(code) ?? throw new ArgumentException($"Unknown code: {code}", nameof(code));
}

/// <summary>Extension methods for reading <see cref="Recruit.Extensions"/> from FHIR resources.</summary>
public static class RecruitFhirExtensions
{
    /// <summary>Gets the value of extension <c>https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-observation-derived-from-library</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static ResourceReference? GetEligibilityObservationDerivedFromLibrary(
        this IExtendable resource
    ) =>
        resource.GetExtensionValue<ResourceReference>(
            "https://miracum.github.io/recruit/fhir/StructureDefinition/eligibility-observation-derived-from-library"
        );

    /// <summary>Gets the value of extension <c>https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study</c> from <paramref name="resource"/>, or <c>null</c> if absent.</summary>
    public static ResourceReference? GetScreeningListBelongsToStudy(this IExtendable resource) =>
        resource.GetExtensionValue<ResourceReference>(
            "https://miracum.github.io/recruit/fhir/StructureDefinition/screening-list-belongs-to-study"
        );
}
