---
apiVersion: v1
kind: Secret
metadata:
  name: recruit-ohdsi-db-app-user
type: kubernetes.io/basic-auth
stringData:
  password: recruit-ohdsi
  username: ohdsi
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: recruit-ohdsi-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
  storage:
    size: 64Gi
  bootstrap:
    initdb:
      database: ohdsi
      owner: ohdsi
      secret:
        name: recruit-ohdsi-db-app-user
---
apiVersion: v1
kind: Secret
metadata:
  name: recruit-fhir-server-db-app-user
type: kubernetes.io/basic-auth
stringData:
  password: recruit-fhir-server
  username: fhir_server_user
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: recruit-fhir-server-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
  storage:
    size: 64Gi
  bootstrap:
    initdb:
      database: fhir_server
      owner: fhir_server_user
      secret:
        name: recruit-fhir-server-db-app-user
---
apiVersion: v1
kind: Secret
metadata:
  name: vfps-db-app-user
type: kubernetes.io/basic-auth
stringData:
  password: vfps
  username: vfps_user
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vfps-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
  storage:
    size: 64Gi
  bootstrap:
    initdb:
      database: vfps
      owner: vfps_user
      secret:
        name: vfps-db-app-user
---
apiVersion: v1
kind: Secret
metadata:
  name: recruit-notify-db-app-user
type: kubernetes.io/basic-auth
stringData:
  password: notify
  username: notify_user
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: recruit-notify-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
  storage:
    size: 64Gi
  bootstrap:
    initdb:
      database: notify_jobstore
      owner: notify_user
      secret:
        name: recruit-notify-db-app-user
