service:
  type: NodePort
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
      nodePort: 30001
