// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecruIT.List.Data;
using RecruIT.List.Models;

#nullable disable

namespace RecruIT.List.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_channel", new[] { "email", "in_app" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trial_permission_level", new[] { "coordinator", "trial_admin", "viewer" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecruIT.List.Data.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<NotificationChannel>("Channel")
                        .HasColumnType("notification_channel")
                        .HasColumnName("channel");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("NotificationEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_event_id");

                    b.Property<Guid>("NotificationSubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_subscription_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_deliveries");

                    b.HasIndex("NotificationEventId")
                        .HasDatabaseName("ix_notification_deliveries_notification_event_id");

                    b.HasIndex("NotificationSubscriptionId")
                        .HasDatabaseName("ix_notification_deliveries_notification_subscription_id");

                    b.HasIndex("Channel", "SentAt", "ScheduledFor")
                        .HasDatabaseName("ix_notification_deliveries_channel_sent_at_scheduled_for");

                    b.HasIndex("SubjectId", "Channel", "ReadAt")
                        .HasDatabaseName("ix_notification_deliveries_subject_id_channel_read_at");

                    b.ToTable("notification_deliveries", (string)null);
                });

            modelBuilder.Entity("RecruIT.List.Data.Entities.NotificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedupe_key");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PatientDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_display_name");

                    b.Property<string>("PatientReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_reference");

                    b.Property<string>("TrialIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier");

                    b.HasKey("Id")
                        .HasName("pk_notification_events");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_events_dedupe_key");

                    b.HasIndex("TrialIdentifier", "OccurredAt")
                        .HasDatabaseName("ix_notification_events_trial_identifier_occurred_at");

                    b.ToTable("notification_events", (string)null);
                });

            modelBuilder.Entity("RecruIT.List.Data.Entities.NotificationSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<TimeOnly?>("TimeOfDay")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_of_day");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("TrialIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notification_subscriptions");

                    b.HasIndex("TrialIdentifier", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_subscriptions_trial_identifier_subject_id");

                    b.ToTable("notification_subscriptions", (string)null);
                });

            modelBuilder.Entity("RecruIT.List.Data.Entities.PollCursor", b =>
                {
                    b.Property<string>("ListId")
                        .HasColumnType("text")
                        .HasColumnName("list_id");

                    b.Property<string>("LastSeenVersionId")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_seen_version_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ListId")
                        .HasName("pk_poll_cursors");

                    b.ToTable("poll_cursors", (string)null);
                });

            modelBuilder.Entity("RecruIT.List.Data.Entities.ScreeningNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_display_name");

                    b.Property<string>("AuthorSubjectId")
                        .HasColumnType("text")
                        .HasColumnName("author_subject_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResearchSubjectIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("research_subject_identifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("TrialIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier");

                    b.HasKey("Id")
                        .HasName("pk_screening_notes");

                    b.HasIndex("ResearchSubjectIdentifier")
                        .HasDatabaseName("ix_screening_notes_research_subject_identifier");

                    b.ToTable("screening_notes", (string)null);
                });

            modelBuilder.Entity("RecruIT.List.Data.Entities.TrialAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("granted_by");

                    b.Property<TrialPermissionLevel>("Level")
                        .HasColumnType("trial_permission_level")
                        .HasColumnName("level");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("TrialIdentifierSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier_system");

                    b.Property<string>("TrialIdentifierValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trial_access_grants");

                    b.HasIndex("TrialIdentifierSystem", "TrialIdentifierValue", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_trial_access_grants_trial_identifier_system_trial_identifie");

                    b.ToTable("trial_access_grants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
