trino:
  datasource:
    url: "jdbc:trino://localhost:8080/fhir/default"
    username: "trino"
    password: ""

fhir:
  url: "http://recruit-fhir-server.127.0.0.1.nip.io/fhir"

# to configure logging levels
logging:
  level:
    org:
      springframework: "DEBUG"
      miracum:
        recruit:
          query: "DEBUG"
