apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: recruit
build:
  artifacts:
    - image: ghcr.io/miracum/recruit/query
      jib:
        project: query
        type: gradle
    - image: ghcr.io/miracum/recruit/notify
      jib:
        project: notify
        type: gradle
    - image: ghcr.io/miracum/recruit/list
      context: list
      docker:
        dockerfile: Dockerfile
        buildArgs:
          GIT_REF: skaffold
          VERSION: skaffold
  local:
    push: false
    tryImportMissing: true
    useBuildkit: true
manifests:
  helm:
    flags:
      install:
        - --timeout=15m
    releases:
      - name: recruit
        chartPath: ../charts/recruit
        createNamespace: true
        namespace: recruit
        valuesFiles:
          - hack/k8s/values-dev.yaml
        wait: true
        skipBuildDependencies: true
deploy:
  helm:
    releases:
      - name: recruit
        chartPath: helm
        createNamespace: true
        namespace: recruit
        valuesFiles:
          - hack/k8s/values-dev.yaml
        skipBuildDependencies: true
    flags:
      install:
        - --timeout=15m
