apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: recruit
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: ghcr.io/miracum/recruit/query
      jib:
        type: gradle
        project: query
        args:
          - "jibDockerBuild"
    - image: ghcr.io/miracum/recruit/notify
      jib:
        type: gradle
        project: notify
        args:
          - "jibDockerBuild"
    - image: ghcr.io/miracum/recruit/list
      context: list
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: recruit
        wait: true
        remoteChart: recruit
        recreatePods: true
        repo: https://miracum.github.io/charts
        version: 9.2.1
        setValues:
          fhirserver.postgresql.auth.postgresPassword: fhir
          ohdsi.postgresql.auth.postgresPassword: ohdsi
        artifactOverrides:
          query.image: ghcr.io/miracum/recruit/query
          notify.image: ghcr.io/miracum/recruit/notify
          list.image: ghcr.io/miracum/recruit/list
        imageStrategy:
          helm:
            explicitRegistry: true
