{{- if and .Values.listNext.enabled .Values.listNext.database.username (not .Values.listNext.database.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "list-next-db" }}
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
    app.kubernetes.io/component: list-next
type: Opaque
data:
  db-password: {{ .Values.listNext.database.password | b64enc | quote }}
{{- end }}
