{{- if and .Values.listNext.enabled .Values.listNext.auth.enabled (not .Values.listNext.auth.oidc.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "list-next-oidc" }}
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
    app.kubernetes.io/component: list-next
type: Opaque
data:
  oidc-client-secret: {{ .Values.listNext.auth.oidc.clientSecret | b64enc | quote }}
{{- end }}
