{{- with .Values.listNext -}}
{{- if and .enabled .podDisruptionBudget.enabled }}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: {{ include "recruit.fullname" $ }}-list-next
  labels:
    {{- include "recruit.labels" $ | nindent 4 }}
spec:
  {{- if .podDisruptionBudget.minAvailable }}
  minAvailable: {{ .podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "recruit.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: list-next
{{- end }}
{{- end }}
