{{- if and .Values.listNext.enabled (not .Values.listNext.notifyMailer.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "list-next-smtp" }}
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
    app.kubernetes.io/component: list-next
type: Opaque
data:
  {{- if .Values.mailhog.enabled }}
  smtp-password: ""
  {{- else }}
  smtp-password: {{ .Values.listNext.notifyMailer.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}
