{{- with .Values.queryFhirTrino -}}
{{- if .enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "recruit.fullname" $ }}-query-fhir-trino
  labels:
    {{- include "recruit.labels" $ | nindent 4 }}
    app.kubernetes.io/component: query-fhir-trino
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "recruit.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: query-fhir-trino
{{- end -}}
{{- end -}}
