{{- if .Values.queryFhirTrino.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "recruit.fullname" . }}-query-fhir-trino
  labels:
    {{- include "recruit.labels" . | nindent 4 }}
  {{- with .Values.queryFhirTrino.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
