{{- with .Values.queryFhirTrino -}}
{{- if and .enabled (not .trino.auth.existingSecret.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "recruit.fullname" $ ) "query-fhir-trino-secret"  }}
  labels:
    {{- include "recruit.labels" $ | nindent 4 }}
    app.kubernetes.io/component: query-fhir-trino
type: Opaque
data:
  trino-password: {{ include "recruit.trino.password" $ | b64enc | quote }}
{{- end -}}
{{- end -}}
