// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using list.Data;
using list.Models;

#nullable disable

namespace list.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trial_permission_level", new[] { "coordinator", "trial_admin", "viewer" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("list.Data.Entities.TrialAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("granted_by");

                    b.Property<TrialPermissionLevel>("Level")
                        .HasColumnType("trial_permission_level")
                        .HasColumnName("level");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("TrialIdentifierSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier_system");

                    b.Property<string>("TrialIdentifierValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trial_access_grants");

                    b.HasIndex("TrialIdentifierSystem", "TrialIdentifierValue", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_trial_access_grants_trial_identifier_system_trial_identifie");

                    b.ToTable("trial_access_grants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
