// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using list.Data;
using list.Models;

#nullable disable

namespace list.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_channel", new[] { "email" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "trial_permission_level", new[] { "coordinator", "trial_admin", "viewer" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("list.Data.Entities.NotificationRecipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<NotificationChannel>("Channel")
                        .HasColumnType("notification_channel")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("TrialIdentifierSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier_system");

                    b.Property<string>("TrialIdentifierValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier_value");

                    b.HasKey("Id")
                        .HasName("pk_notification_recipients");

                    b.HasIndex("TrialIdentifierSystem", "TrialIdentifierValue", "Email", "Channel")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_recipients_trial_identifier_system_trial_ident");

                    b.ToTable("notification_recipients", (string)null);
                });

            modelBuilder.Entity("list.Data.Entities.PollCursor", b =>
                {
                    b.Property<string>("ListId")
                        .HasColumnType("text")
                        .HasColumnName("list_id");

                    b.Property<string>("LastSeenVersionId")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_seen_version_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ListId")
                        .HasName("pk_poll_cursors");

                    b.ToTable("poll_cursors", (string)null);
                });

            modelBuilder.Entity("list.Data.Entities.ScreeningNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_display_name");

                    b.Property<string>("AuthorSubjectId")
                        .HasColumnType("text")
                        .HasColumnName("author_subject_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ResearchSubjectIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("research_subject_identifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("TrialIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier");

                    b.HasKey("Id")
                        .HasName("pk_screening_notes");

                    b.HasIndex("ResearchSubjectIdentifier")
                        .HasDatabaseName("ix_screening_notes_research_subject_identifier");

                    b.ToTable("screening_notes", (string)null);
                });

            modelBuilder.Entity("list.Data.Entities.TrialAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("granted_by");

                    b.Property<TrialPermissionLevel>("Level")
                        .HasColumnType("trial_permission_level")
                        .HasColumnName("level");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("TrialIdentifierSystem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier_system");

                    b.Property<string>("TrialIdentifierValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trial_identifier_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trial_access_grants");

                    b.HasIndex("TrialIdentifierSystem", "TrialIdentifierValue", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_trial_access_grants_trial_identifier_system_trial_identifie");

                    b.ToTable("trial_access_grants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
