name: "build container image"

permissions: {}

on:
  workflow_call:
    inputs:
      module-name:
        description: "Name of the project inside the /src/ dir"
        type: string
        required: true
      context:
        description: "the docker build context path"
        type: string
        default: .
        required: false
    outputs:
      image-tag:
        description: "The image tag that was built"
        value: ${{ jobs.build.outputs.image-tags }}

jobs:
  build:
    name: build container image
    uses: miracum/.github/.github/workflows/standard-build.yaml@1478f7e298f11e96e4585dee4afdce8fabc2e162 # v1.20.5
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
      actions: read
      security-events: write
    with:
      image: ghcr.io/${{ github.repository }}/${{ inputs.module-name }}
      build-context: ${{ inputs.context }}
      enable-build-test-layer: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
