name: check links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

permissions: read-all

jobs:
  check-links:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@7cd0af4c74a61395d455af97419279d86aafaede # v2.0.2
        with:
          args: "--config=.lychee.toml ."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Look for an existing issue
        id: last-issue
        uses: micalevisk/last-issue-action@0d40124cc99ac8601c2516007f0c98ef3d27537b # v2.3.0
        with:
          state: open
          labels: link-check

      - name: Create Issue From File
        if: ${{ env.lychee_exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5.0.1
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          issue-number: ${{ steps.last-issue.outputs.issue_number }}
          labels: report, automated issue, link-check
