name: check links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

permissions: read-all

jobs:
  check-links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@9ace499fe66cee282a29eaa628fdac2c72fa087f # tag=v1.6.1
        with:
          args: "--config=.lychee.toml ."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # tag=v4.0.1
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
