name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      # If you want a workflow to run when stable and pre-releases publish, subscribe to published instead of released and prereleased.
      # <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release>
      - published
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      actions: read
      packages: write
      id-token: write
    strategy:
      matrix:
        include:
          - module: "query"
            context: "src/"
          - module: "notify"
            context: "src/"
          - module: "list"
            context: "src/list/"
          - module: "query-fhir-trino"
            context: "src/"
    uses: miracum/.github/.github/workflows/standard-build.yaml@1478f7e298f11e96e4585dee4afdce8fabc2e162 # v1.20.5
    with:
      image: ghcr.io/${{ github.repository }}/${{ matrix.module }}
      build-context: ${{ matrix.context }}
      enable-build-test-layer: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: test
    runs-on: ubuntu-24.04
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: "query"
            e2e-test-directory: "tests/e2e/"
          - module: "notify"
            e2e-test-directory: "tests/e2e/"
          - module: "query-fhir-trino"
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/${{ matrix.module }}
      # the image tag is the same for all modules, we can just use the last matrix job's output as they all share the same tag.
      IMAGE_TAG: ${{ needs.build.outputs.image-version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # unfortunately we need to re-compute the artifact name as we can't access the matrix job's outputs.
      - uses: rlespinasse/slugify-value@a4879db1eb3db9bbee01dca36f98a8236c2b8239 # v1.4.0
        id: slugify-image
        with:
          key: BUILD_IMAGE
          value: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          publish-env: false
          slug-maxlength: nolimit

      - name: Download image
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ steps.slugify-image.outputs.slug }}
          path: /tmp

      - name: Load image
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker load --input /tmp/image.tar
          docker image ls

      - name: Pull image if not in PR
        shell: bash
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker pull "${IMAGE_NAME}:${IMAGE_TAG}"
          docker image ls -a

      - name: Run container structure tests
        shell: bash
        run: |
          curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/download/v1.22.1/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64

          ./container-structure-test-linux-amd64 test --image="${IMAGE_NAME}:${IMAGE_TAG}" --config=tests/container-structure/common-tests.yaml

      - name: Run isolated smoke test
        if: ${{ matrix.e2e-test-directory != ''}}
        shell: bash
        working-directory: src/${{ matrix.module }}
        env:
          E2E_TEST_DIRECTORY: ${{ matrix.e2e-test-directory }}
        run: |
          docker compose -f "${E2E_TEST_DIRECTORY}/docker-compose.yaml" build
          docker compose -f "${E2E_TEST_DIRECTORY}/docker-compose.yaml" run tester

      - name: Print test logs and stop all running containers
        if: ${{ matrix.e2e-test-directory != '' && always()}}
        shell: bash
        working-directory: src/${{ matrix.module }}
        continue-on-error: true
        env:
          E2E_TEST_DIRECTORY: ${{ matrix.e2e-test-directory }}
        run: |
          docker compose -f "${E2E_TEST_DIRECTORY}/docker-compose.yaml" logs
          docker compose -f "${E2E_TEST_DIRECTORY}/docker-compose.yaml" down --volumes --remove-orphans

  k8s-test:
    needs:
      - build
      - test
    uses: ./.github/workflows/test-k8s-installation.yaml
    with:
      image-tag: ${{ needs.build.outputs.image-version }}

  docker-compose-test:
    needs:
      - build
      - test
    uses: ./.github/workflows/test-compose-installation.yaml
    with:
      image-tag: ${{ needs.build.outputs.image-version }}

  release:
    # the docker compose image tags only change on releases, so
    # it's sufficient to just run tests then.
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      actions: read
      contents: write # for release notes
      # for creating OIDC tokens for signing.
      id-token: write
      packages: write # for uploading container images, signatures, and attestations.
    needs:
      - k8s-test
      - docker-compose-test
    uses: ./.github/workflows/release.yaml
    secrets:
      token: ${{ secrets.MIRACUM_BOT_SEMANTIC_RELEASE_TOKEN }}

  lint:
    uses: miracum/.github/.github/workflows/standard-lint.yaml@e80245abb031a27f87d0e07eeb6f5f54a82a46b8 # v1.20.4
    permissions:
      contents: read
      pull-requests: write
      issues: write
      security-events: write
      actions: read
    with:
      enable-validate-gradle-wrapper: false
      codeql-languages: '["python", "javascript", "java", "csharp"]'
      enable-codeql: true
      enable-verify-base-image-signature: false
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
