name: test-deployments
on:
  pull_request:
    paths:
      - "docker-compose/**"
    branches:
      - master

permissions: read-all

jobs:
  test-compose-deployment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Deploy using Docker Compose in staging mode
        run: |
          docker compose \
            --project-name=recruit \
            --env-file=docker-compose/.staging.env \
            -f docker-compose/docker-compose.yaml \
            -f docker-compose/docker-compose.staging.yaml up --detach

      - name: List containers
        run: |
          docker compose \
            --project-name=recruit \
            --env-file=docker-compose/.staging.env \
            -f docker-compose/docker-compose.yaml \
            -f docker-compose/docker-compose.staging.yaml ps

      - name: Run basic health probes
        run: |
          docker compose \
            --project-name=recruit \
            --env-file=docker-compose/.staging.env \
            -f docker-compose/docker-compose.yaml \
            -f docker-compose/docker-compose.staging.yaml \
            -f docker-compose/docker-compose.probe.yaml run health-probes

      - name: Display logs
        if: always()
        run: |
          docker compose \
            --project-name=recruit \
            --env-file=docker-compose/.staging.env \
            -f docker-compose/docker-compose.yaml \
            -f docker-compose/docker-compose.staging.yaml logs
