name: validate-fhir-resources

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  validate-fhir-resource:
    name: Validate FHIR resources
    runs-on: ubuntu-24.04
    container: ghcr.io/miracum/ig-build-tools:v2.2.46@sha256:00ab42bcf4f527b5c4f7415dc8bbcd65aa05f21f5ddfa4303bdaf7642789d862
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Restore FHIR package dependencies
        working-directory: fhir/
        run: |
          fhir restore

      - name: Validate generated FHIR resources
        working-directory: fhir/
        shell: bash
        run: |
          find ../src/ -name "*.fhir.json" -exec fhir validate --verbose --fail "{}" \;
