# For some reason megalinter ignores the yamllint config
# and attempts to lint charts/recruit/templates causing
# it to fail constantly. So we run yamllint as a dedicated step
# instead.
name: yamllint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions: read-all

jobs:
  yamllint:
    runs-on: ubuntu-24.04
    # contains yamllint
    container: ghcr.io/chgl/kube-powertools:v2.3.36@sha256:1424a809e85eda3a6d7afb2386bdc3b9ac03b2b5244924a7be4851b15a2eca4f
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run yamllint
        run: yamllint -c .yamllint.yaml .
